require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ConferencesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Conference. As you add validations to Conference, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    return {
      name: "Nine Worlds 2015",
      start_date: "2015-08-07",
      end_date: "2015-08-09"
    }
  }

  let(:invalid_attributes) {
    return{
      unexpected: "attribute",
      name: 1000,
      start_date: "not a date",
      end_date: "0000-00-32"
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConferencesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all conferences as @conferences" do
      conference = Conference.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:conferences)).to eq([conference])
    end
  end

  describe "GET #show" do
    it "assigns the requested conference as @conference" do
      conference = Conference.create! valid_attributes
      get :show, {:id => conference.to_param}, valid_session
      expect(assigns(:conference)).to eq(conference)
    end
  end

  describe "GET #new" do
    it "assigns a new conference as @conference" do
      get :new, {}, valid_session
      expect(assigns(:conference)).to be_a_new(Conference)
    end
  end

  describe "GET #edit" do
    it "assigns the requested conference as @conference" do
      conference = Conference.create! valid_attributes
      get :edit, {:id => conference.to_param}, valid_session
      expect(assigns(:conference)).to eq(conference)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Conference" do
        expect {
          post :create, {:conference => valid_attributes}, valid_session
        }.to change(Conference, :count).by(1)
      end

      it "assigns a newly created conference as @conference" do
        post :create, {:conference => valid_attributes}, valid_session
        expect(assigns(:conference)).to be_a(Conference)
        expect(assigns(:conference)).to be_persisted
      end

      it "redirects to the created conference" do
        post :create, {:conference => valid_attributes}, valid_session
        expect(response).to redirect_to(Conference.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved conference as @conference" do
        post :create, {:conference => invalid_attributes}, valid_session
        expect(assigns(:conference)).to be_a_new(Conference)
      end

      it "re-renders the 'new' template" do
        post :create, {:conference => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested conference" do
        conference = Conference.create! valid_attributes
        put :update, {:id => conference.to_param, :conference => new_attributes}, valid_session
        conference.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested conference as @conference" do
        conference = Conference.create! valid_attributes
        put :update, {:id => conference.to_param, :conference => valid_attributes}, valid_session
        expect(assigns(:conference)).to eq(conference)
      end

      it "redirects to the conference" do
        conference = Conference.create! valid_attributes
        put :update, {:id => conference.to_param, :conference => valid_attributes}, valid_session
        expect(response).to redirect_to(conference)
      end
    end

    context "with invalid params" do
      it "assigns the conference as @conference" do
        conference = Conference.create! valid_attributes
        put :update, {:id => conference.to_param, :conference => invalid_attributes}, valid_session
        expect(assigns(:conference)).to eq(conference)
      end

      it "re-renders the 'edit' template" do
        conference = Conference.create! valid_attributes
        put :update, {:id => conference.to_param, :conference => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested conference" do
      conference = Conference.create! valid_attributes
      expect {
        delete :destroy, {:id => conference.to_param}, valid_session
      }.to change(Conference, :count).by(-1)
    end

    it "redirects to the conferences list" do
      conference = Conference.create! valid_attributes
      delete :destroy, {:id => conference.to_param}, valid_session
      expect(response).to redirect_to(conferences_url)
    end
  end

end
